# Generated by Django 4.0 on 2023-07-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_address_number_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='end_price',
            field=models.FloatField(default=0),
        ),
    ]
